name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        pwd
        ls -a
    - name: Install PlatformIO
      run: |
        pip install wheel
        pip install -U platformio
        # $HOME/.platformio/penv/bin/platformio --version
        find $HOME -name platformio
