name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v1
      
    - name: Set
      run: echo ::set-env name=MYVAR::$(echo "$PATH:$HOME")
      
    - name: Run a multi-line script
      run: |
        pwd
        ls -a
        FOO=test
        echo "FOO is '$FOO'"
        echo "MYVAR is '$MYVAR'"
        
    - name: Cache PlatformIO
      id: platformio-cache-id
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache PlatformIO Binary
      id: platformio-bin-cache-id
      uses: actions/cache@v1
      with:
        path: ~/.local
        key: ${{ runner.os }}-platformio-bin

    - name: Install PlatformIO
      if: steps.platformio-cache-id.outputs.cache-hit != 'true'
      run: |
        pip install -r requirements.txt
        $HOME/.local/bin/platformio --version
        
    - name: Install dfu-util
      run: |
        sudo apt-get --assume-yes install dfu-util
        dfu-util --version

    - name: Build Stepper
      run: |
        $HOME/.local/bin/platformio run -d stepper -v
        
    - name: Build MAX6675
      run: |
        $HOME/.local/bin/platformio run -d max6675 -v
