name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MYVAR: ${{ format('{0}:{1}', {{ env.PATH }}, {{ env.HOME }} ) }}
      
    steps:
    - uses: actions/checkout@v1
      
    - name: Check environment
      run: echo $MYVAR
      
    - name: Run a multi-line script
      run: |
        pwd
        ls -a
        FOO=test
        echo "FOO is '$FOO'"
        
    - name: Install PlatformIO
      run: |
        sudo apt-get --assume-yes install dfu-util
        pip install wheel
        pip install -U platformio
        $HOME/.local/bin/platformio --version
        dfu-util --version
        
    - name: Build Stepper
      run: |
        $HOME/.local/bin/platformio run -d stepper -v
        
    - name: Build MAX6675
      run: |
        $HOME/.local/bin/platformio run -d max6675 -v
